O_FILES :=  $(BUILD_DIR)/asm/sinit.o \
$(BUILD_DIR)/asm/code/CSimsApp.o \
$(BUILD_DIR)/asm/code/MacGIMEX.o \
$(BUILD_DIR)/asm/code/MacMain.o \
$(BUILD_DIR)/asm/code/MacStringMunger.o \
$(BUILD_DIR)/asm/code/LargeInt.o \
$(BUILD_DIR)/asm/code/RealMath.o \
$(BUILD_DIR)/asm/code/CGameApp.o \
$(BUILD_DIR)/asm/code/CDrawSprocket.o \
$(BUILD_DIR)/asm/code/CQuickTImePlayer.o \
$(BUILD_DIR)/asm/code/Mac3D.o \
$(BUILD_DIR)/asm/code/MacFiles.o \
$(BUILD_DIR)/asm/code/MacPortUtils.o \
$(BUILD_DIR)/asm/code/MacSndUtils.o \
$(BUILD_DIR)/asm/code/MacTiming.o \
$(BUILD_DIR)/asm/code/MacUtils.o \
$(BUILD_DIR)/asm/code/MSLOverrides.o \
$(BUILD_DIR)/asm/code/Win32D3D.o \
$(BUILD_DIR)/asm/code/Win32DDraw.o \
$(BUILD_DIR)/asm/code/Win32DDraw2.o \
$(BUILD_DIR)/asm/code/Win32DDraw4.o \
$(BUILD_DIR)/asm/code/Win32DDraw7.o \
$(BUILD_DIR)/asm/code/Win32DSound.o \
$(BUILD_DIR)/asm/code/Win32DSound3D.o \
$(BUILD_DIR)/asm/code/Win32DX7Stubs.o \
$(BUILD_DIR)/asm/code/Win32Files.o \
$(BUILD_DIR)/asm/code/Win32FindFirst.o \
$(BUILD_DIR)/asm/code/Win32HANDLE.o \
$(BUILD_DIR)/asm/code/Win32HWND.o \
$(BUILD_DIR)/asm/code/Win32MMSystem.o \
$(BUILD_DIR)/asm/code/Win32ObjBase.o \
$(BUILD_DIR)/asm/code/Win32RuntimeExtras.o \
$(BUILD_DIR)/asm/code/Win32ShellAPI.o \
$(BUILD_DIR)/asm/code/Win32Threads.o \
$(BUILD_DIR)/asm/code/Win32WinBase.o \
$(BUILD_DIR)/asm/code/Win32WinGDI.o \
$(BUILD_DIR)/asm/code/Win32WinNLS.o \
$(BUILD_DIR)/asm/code/Win32WinReg.o \
$(BUILD_DIR)/asm/code/Win32WinUser.o \
$(BUILD_DIR)/asm/code/Win32WinVer.o \
$(BUILD_DIR)/asm/code/LMutexSemaphore.o \
$(BUILD_DIR)/asm/code/LSemaphore.o \
$(BUILD_DIR)/asm/code/LThread.o \
$(BUILD_DIR)/asm/code/LThreadLow.o \
$(BUILD_DIR)/asm/code/UThread.o \
$(BUILD_DIR)/asm/code/UEnvironment.o \
$(BUILD_DIR)/asm/code/AnimTable.o \
$(BUILD_DIR)/asm/code/AttribFile.o \
$(BUILD_DIR)/asm/code/AttribTable.o \
$(BUILD_DIR)/asm/code/behavior.o \
$(BUILD_DIR)/asm/code/Careers.o \
$(BUILD_DIR)/asm/code/CatalogResource.o \
$(BUILD_DIR)/asm/code/ChainResFile.o \
$(BUILD_DIR)/asm/code/ComeSeeMe.o \
$(BUILD_DIR)/asm/code/Commander.o \
$(BUILD_DIR)/asm/code/ctilept.o \
$(BUILD_DIR)/asm/code/DrawGroup.o \
$(BUILD_DIR)/asm/code/EditPerson.o \
$(BUILD_DIR)/asm/code/Family.o \
$(BUILD_DIR)/asm/code/FamilyHistory.o \
$(BUILD_DIR)/asm/code/filelist.o \
$(BUILD_DIR)/asm/code/FileUtils.o \
$(BUILD_DIR)/asm/code/flatfile.o \
$(BUILD_DIR)/asm/code/FloatConstants.o \
$(BUILD_DIR)/asm/code/Globs.o \
$(BUILD_DIR)/asm/code/GUIDTranslation.o \
$(BUILD_DIR)/asm/code/House.o \
$(BUILD_DIR)/asm/code/IconGroup.o \
$(BUILD_DIR)/asm/code/IFFResFile.o \
$(BUILD_DIR)/asm/code/IFFResFile2.o \
$(BUILD_DIR)/asm/code/Interaction.o \
$(BUILD_DIR)/asm/code/memwrap.o \
$(BUILD_DIR)/asm/code/menuwrap.o \
$(BUILD_DIR)/asm/code/Motive.o \
$(BUILD_DIR)/asm/code/MotiveCurve.o \
$(BUILD_DIR)/asm/code/MotiveEffects.o \
$(BUILD_DIR)/asm/code/mouseobject.o \
$(BUILD_DIR)/asm/code/MTObject.o \
$(BUILD_DIR)/asm/code/Neighbor.o \
$(BUILD_DIR)/asm/code/Neighborhood.o \
$(BUILD_DIR)/asm/code/newarray2d.o \
$(BUILD_DIR)/asm/code/ObjDefinition.o \
$(BUILD_DIR)/asm/code/object.o \
$(BUILD_DIR)/asm/code/ObjectDialog.o \
$(BUILD_DIR)/asm/code/ObjectDraw.o \
$(BUILD_DIR)/asm/code/ObjectErr.o \
$(BUILD_DIR)/asm/code/ObjectFolder.o \
$(BUILD_DIR)/asm/code/ObjectIterator.o \
$(BUILD_DIR)/asm/code/ObjectModule.o \
$(BUILD_DIR)/asm/code/ObjectSim.o \
$(BUILD_DIR)/asm/code/ObjectStream.o \
$(BUILD_DIR)/asm/code/ObjectTypeAttributes.o \
$(BUILD_DIR)/asm/code/ObjFnTable.o \
$(BUILD_DIR)/asm/code/objresfile.o \
$(BUILD_DIR)/asm/code/ObjSelector.o \
$(BUILD_DIR)/asm/code/ObjTestSim.o \
$(BUILD_DIR)/asm/code/offscrn.o \
$(BUILD_DIR)/asm/code/person.o \
$(BUILD_DIR)/asm/code/Piecewise.o \
$(BUILD_DIR)/asm/code/PoolLayer.o \
$(BUILD_DIR)/asm/code/PopupHead.o \
$(BUILD_DIR)/asm/code/portal.o \
$(BUILD_DIR)/asm/code/porttype.o \
$(BUILD_DIR)/asm/code/PStrings.o \
$(BUILD_DIR)/asm/code/Recon.o \
$(BUILD_DIR)/asm/code/RelMatrix.o \
$(BUILD_DIR)/asm/code/resfile.o \
$(BUILD_DIR)/asm/code/ResolveResFile.o \
$(BUILD_DIR)/asm/code/Rooms.o \
$(BUILD_DIR)/asm/code/Routing.o \
$(BUILD_DIR)/asm/code/SeqResFile.o \
$(BUILD_DIR)/asm/code/SimLogging.o \
$(BUILD_DIR)/asm/code/Simulator.o \
$(BUILD_DIR)/asm/code/Slots.o \
$(BUILD_DIR)/asm/code/Spreadsheet.o \
$(BUILD_DIR)/asm/code/srand.o \
$(BUILD_DIR)/asm/code/StdResFile.o \
$(BUILD_DIR)/asm/code/StringBuffer.o \
$(BUILD_DIR)/asm/code/strset.o \
$(BUILD_DIR)/asm/code/StubObject.o \
$(BUILD_DIR)/asm/code/SuitRegExp.o \
$(BUILD_DIR)/asm/code/SuitTex.o \
$(BUILD_DIR)/asm/code/tbfreqprobe.o \
$(BUILD_DIR)/asm/code/tbintervalprobe.o \
$(BUILD_DIR)/asm/code/tbsiggen.o \
$(BUILD_DIR)/asm/code/timebase.o \
$(BUILD_DIR)/asm/code/TimeOfDay.o \
$(BUILD_DIR)/asm/code/TreeConstants.o \
$(BUILD_DIR)/asm/code/TreeProperties.o \
$(BUILD_DIR)/asm/code/treesim.o \
$(BUILD_DIR)/asm/code/treetab.o \
$(BUILD_DIR)/asm/code/TutorialEffects.o \
$(BUILD_DIR)/asm/code/viewer.o \
$(BUILD_DIR)/asm/code/walls.o \
$(BUILD_DIR)/asm/code/WaterLayer.o \
$(BUILD_DIR)/asm/code/world.o \
$(BUILD_DIR)/asm/code/xassert.o \
$(BUILD_DIR)/asm/code/xlingo.o \
$(BUILD_DIR)/asm/code/XRouting.o \
$(BUILD_DIR)/asm/code/Zodiac.o \
$(BUILD_DIR)/asm/code/GameTools.o \
$(BUILD_DIR)/asm/code/GroundTool.o \
$(BUILD_DIR)/asm/code/LevelTool.o \
$(BUILD_DIR)/asm/code/MoveTool.o \
$(BUILD_DIR)/asm/code/newfloortool.o \
$(BUILD_DIR)/asm/code/NewWallpaperTool.o \
$(BUILD_DIR)/asm/code/newwalltool.o \
$(BUILD_DIR)/asm/code/ObjectUndoable.o \
$(BUILD_DIR)/asm/code/ObjPickerTool.o \
$(BUILD_DIR)/asm/code/PoolTool.o \
$(BUILD_DIR)/asm/code/RoofUndoable.o \
$(BUILD_DIR)/asm/code/TerrainTools.o \
$(BUILD_DIR)/asm/code/TerrainUndoable.o \
$(BUILD_DIR)/asm/code/TileTool.o \
$(BUILD_DIR)/asm/code/tools.o \
$(BUILD_DIR)/asm/code/undoable.o \
$(BUILD_DIR)/asm/code/undomanager.o \
$(BUILD_DIR)/asm/code/WallpaperUndoable.o \
$(BUILD_DIR)/asm/code/wallundoable.o \
$(BUILD_DIR)/asm/code/WaterTool.o \
$(BUILD_DIR)/asm/code/AlphaZSpriteBlitter.o \
$(BUILD_DIR)/asm/code/AnimDeviceSub.o \
$(BUILD_DIR)/asm/code/ArrayDecompressor.o \
$(BUILD_DIR)/asm/code/BlitIntoWorld.o \
$(BUILD_DIR)/asm/code/BrightnessPalette.o \
$(BUILD_DIR)/asm/code/CanonicalLightMap.o \
$(BUILD_DIR)/asm/code/ColorSwatch.o \
$(BUILD_DIR)/asm/code/CutawaySet.o \
$(BUILD_DIR)/asm/code/CutawayWallThickBlitter.o \
$(BUILD_DIR)/asm/code/DarkMap.o \
$(BUILD_DIR)/asm/code/DummyDecompressor.o \
$(BUILD_DIR)/asm/code/FloorBlitter.o \
$(BUILD_DIR)/asm/code/FloorGraphicsMgr.o \
$(BUILD_DIR)/asm/code/FloorLightMap.o \
$(BUILD_DIR)/asm/code/FloorShadowMgr.o \
$(BUILD_DIR)/asm/code/GouraudSwatch.o \
$(BUILD_DIR)/asm/code/GraphicsCheats.o \
$(BUILD_DIR)/asm/code/GridBlitter.o \
$(BUILD_DIR)/asm/code/GViewer.o \
$(BUILD_DIR)/asm/code/HouseViewer.o \
$(BUILD_DIR)/asm/code/isoview.o \
$(BUILD_DIR)/asm/code/Lighting.o \
$(BUILD_DIR)/asm/code/LightingRig.o \
$(BUILD_DIR)/asm/code/LightLayer.o \
$(BUILD_DIR)/asm/code/LightMapSet.o \
$(BUILD_DIR)/asm/code/LitFloorAddBlitter.o \
$(BUILD_DIR)/asm/code/LitFloorBlitter.o \
$(BUILD_DIR)/asm/code/LitWallAddBlitter.o \
$(BUILD_DIR)/asm/code/LitWallBlitter.o \
$(BUILD_DIR)/asm/code/Logo.o \
$(BUILD_DIR)/asm/code/MakeBMP.o \
$(BUILD_DIR)/asm/code/MakeJPEG.o \
$(BUILD_DIR)/asm/code/MapTileSwatch.o \
$(BUILD_DIR)/asm/code/palettemanager.o \
$(BUILD_DIR)/asm/code/palwrap.o \
$(BUILD_DIR)/asm/code/renderloc.o \
$(BUILD_DIR)/asm/code/RGBMorph.o \
$(BUILD_DIR)/asm/code/RLEDecompressor.o \
$(BUILD_DIR)/asm/code/ScaleBitmap.o \
$(BUILD_DIR)/asm/code/ShearedLightMap.o \
$(BUILD_DIR)/asm/code/Spr2Decoder.o \
$(BUILD_DIR)/asm/code/SpriteListInfo.o \
$(BUILD_DIR)/asm/code/StalkerCam.o \
$(BUILD_DIR)/asm/code/StandardBlitter16.o \
$(BUILD_DIR)/asm/code/standardZBlitter16.o \
$(BUILD_DIR)/asm/code/surfutils.o \
$(BUILD_DIR)/asm/code/terrain.o \
$(BUILD_DIR)/asm/code/TerrainLightSource.o \
$(BUILD_DIR)/asm/code/wallblitter.o \
$(BUILD_DIR)/asm/code/WallGraphicsMgr.o \
$(BUILD_DIR)/asm/code/WaterSpr2Decoder.o \
$(BUILD_DIR)/asm/code/xrender.o \
$(BUILD_DIR)/asm/code/XSmoothScroller.o \
$(BUILD_DIR)/asm/code/ZBufferLookup.o \
$(BUILD_DIR)/asm/code/ZSpriteBlitter.o \
$(BUILD_DIR)/asm/code/ActionIcon.o \
$(BUILD_DIR)/asm/code/AverageHistory.o \
$(BUILD_DIR)/asm/code/Catalog.o \
$(BUILD_DIR)/asm/code/CPState.o \
$(BUILD_DIR)/asm/code/DDDSimsView.o \
$(BUILD_DIR)/asm/code/DebugPanel.o \
$(BUILD_DIR)/asm/code/EdgeDetectScroller.o \
$(BUILD_DIR)/asm/code/EventLog.o \
$(BUILD_DIR)/asm/code/Exceptions.o \
$(BUILD_DIR)/asm/code/exporthtml.o \
$(BUILD_DIR)/asm/code/fileiter.o \
$(BUILD_DIR)/asm/code/GIMEXFactory.o \
$(BUILD_DIR)/asm/code/GZBufferBMP.o \
$(BUILD_DIR)/asm/code/MemCrawl.o \
$(BUILD_DIR)/asm/code/MemDebug.o \
$(BUILD_DIR)/asm/code/memdiff.o \
$(BUILD_DIR)/asm/code/MSJEXHND.o \
$(BUILD_DIR)/asm/code/NghInterface.o \
$(BUILD_DIR)/asm/code/ObjectDialogCheat.o \
$(BUILD_DIR)/asm/code/ObjectIcon.o \
$(BUILD_DIR)/asm/code/OptionsMgr.o \
$(BUILD_DIR)/asm/code/PeopleButtons.o \
$(BUILD_DIR)/asm/code/PersonFinder.o \
$(BUILD_DIR)/asm/code/ProcessHeaps.o \
$(BUILD_DIR)/asm/code/scrapbook.o \
$(BUILD_DIR)/asm/code/simplecrypto.o \
$(BUILD_DIR)/asm/code/SimsApp.o \
$(BUILD_DIR)/asm/code/SimsColors.o \
$(BUILD_DIR)/asm/code/SplashScreen.o \
$(BUILD_DIR)/asm/code/TutorialIcon.o \
$(BUILD_DIR)/asm/code/uistrings.o \
$(BUILD_DIR)/asm/code/WinArch.o \
$(BUILD_DIR)/asm/code/WinBudgetDlg.o \
$(BUILD_DIR)/asm/code/winbudgetrow.o \
$(BUILD_DIR)/asm/code/wincampanel.o \
$(BUILD_DIR)/asm/code/WinCatalog.o \
$(BUILD_DIR)/asm/code/WinCatalogPopup.o \
$(BUILD_DIR)/asm/code/WinCPanel.o \
$(BUILD_DIR)/asm/code/WinCredits.o \
$(BUILD_DIR)/asm/code/WinDeltaMeter.o \
$(BUILD_DIR)/asm/code/WinDisposePopup.o \
$(BUILD_DIR)/asm/code/WinEditBio.o \
$(BUILD_DIR)/asm/code/WinHelp.o \
$(BUILD_DIR)/asm/code/WinLivePopup.o \
$(BUILD_DIR)/asm/code/WinLivePopupClient.o \
$(BUILD_DIR)/asm/code/WinMemView.o \
$(BUILD_DIR)/asm/code/WinMotive.o \
$(BUILD_DIR)/asm/code/WinOptions.o \
$(BUILD_DIR)/asm/code/WinPeople.o \
$(BUILD_DIR)/asm/code/WinPersonality.o \
$(BUILD_DIR)/asm/code/WinPictureDialog.o \
$(BUILD_DIR)/asm/code/WinPictureInPicture.o \
$(BUILD_DIR)/asm/code/WinRelationship.o \
$(BUILD_DIR)/asm/code/WinRoofPanel.o \
$(BUILD_DIR)/asm/code/winscrapbook.o \
$(BUILD_DIR)/asm/code/WinSubpanelHouse.o \
$(BUILD_DIR)/asm/code/WinSubpanelJob.o \
$(BUILD_DIR)/asm/code/WinSubpanelReportCard.o \
$(BUILD_DIR)/asm/code/WinSweepMeter.o \
$(BUILD_DIR)/asm/code/WinTextWrap.o \
$(BUILD_DIR)/asm/code/WinTileInfo.o \
$(BUILD_DIR)/asm/code/WinTriRadio.o \
$(BUILD_DIR)/asm/code/WinTriText.o \
$(BUILD_DIR)/asm/code/WinViewControl.o \
$(BUILD_DIR)/asm/code/tilewalls.o \
$(BUILD_DIR)/asm/code/Vertex.o \
$(BUILD_DIR)/asm/code/VertexConfig.o \
$(BUILD_DIR)/asm/code/Wall.o \
$(BUILD_DIR)/asm/code/WallManager.o \
$(BUILD_DIR)/asm/code/PickFamilyItem.o \
$(BUILD_DIR)/asm/code/PickFamilyList.o \
$(BUILD_DIR)/asm/code/PickFamilyPersonInfo.o \
$(BUILD_DIR)/asm/code/WinDesignCharacter.o \
$(BUILD_DIR)/asm/code/WinDesignFamily.o \
$(BUILD_DIR)/asm/code/WinLotBtn.o \
$(BUILD_DIR)/asm/code/WinLotPopup.o \
$(BUILD_DIR)/asm/code/WinPersonalityWidget.o \
$(BUILD_DIR)/asm/code/WinPickFamily.o \
$(BUILD_DIR)/asm/code/WinVitaBtn.o \
$(BUILD_DIR)/asm/code/RoofLayer.o \
$(BUILD_DIR)/asm/code/RoofMeshFactory.o \
$(BUILD_DIR)/asm/code/RoofTile.o \
$(BUILD_DIR)/asm/code/AudioInfo.o \
$(BUILD_DIR)/asm/code/Boxx.o \
$(BUILD_DIR)/asm/code/C2HCache.o \
$(BUILD_DIR)/asm/code/Freshness.o \
$(BUILD_DIR)/asm/code/FreshnessUtil.o \
$(BUILD_DIR)/asm/code/GameSound.o \
$(BUILD_DIR)/asm/code/HitIniFile.o \
$(BUILD_DIR)/asm/code/Listener.o \
$(BUILD_DIR)/asm/code/Patch.o \
$(BUILD_DIR)/asm/code/SoundInfo.o \
$(BUILD_DIR)/asm/code/inigimex.o \
$(BUILD_DIR)/asm/code/resample.o \
$(BUILD_DIR)/asm/code/Sims_gimexfile.o \
$(BUILD_DIR)/asm/code/stdgimex.o \
$(BUILD_DIR)/asm/code/BodyStrings.o \
$(BUILD_DIR)/asm/code/SAnimator.o \
$(BUILD_DIR)/asm/code/skeleton.o \
$(BUILD_DIR)/asm/code/SkillLookup.o \
$(BUILD_DIR)/asm/code/vitaboy.o \
$(BUILD_DIR)/asm/code/GZResMgr.o \
$(BUILD_DIR)/asm/code/GZResMgrRTParser.o \
$(BUILD_DIR)/asm/code/SimsResFac.o \
$(BUILD_DIR)/asm/code/AudioEffectsBusWin.o \
$(BUILD_DIR)/asm/code/DBCFont.o \
$(BUILD_DIR)/asm/code/DBCFontKorean.o \
$(BUILD_DIR)/asm/code/DefaultTTWindow.o \
$(BUILD_DIR)/asm/code/TimePartition.o \
$(BUILD_DIR)/asm/code/dddanimdevice.o \
$(BUILD_DIR)/asm/code/dddcamera.o \
$(BUILD_DIR)/asm/code/DDDConcreteRenderObject.o \
$(BUILD_DIR)/asm/code/DDDD3DStub.o \
$(BUILD_DIR)/asm/code/DDDDamageList.o \
$(BUILD_DIR)/asm/code/ddddevice3d.o \
$(BUILD_DIR)/asm/code/dddlight.o \
$(BUILD_DIR)/asm/code/DDDMaterial.o \
$(BUILD_DIR)/asm/code/DDDMaterialMgr.o \
$(BUILD_DIR)/asm/code/DDDRenderDIPMesh.o \
$(BUILD_DIR)/asm/code/DDDRenderDIPVBMesh.o \
$(BUILD_DIR)/asm/code/DDDRenderDPMesh.o \
$(BUILD_DIR)/asm/code/DDDRenderGroup.o \
$(BUILD_DIR)/asm/code/DDDRenderMesh.o \
$(BUILD_DIR)/asm/code/DDDRenderObject.o \
$(BUILD_DIR)/asm/code/DDDRenderObjectFactory.o \
$(BUILD_DIR)/asm/code/DDDTexture.o \
$(BUILD_DIR)/asm/code/DDDTextureMgr.o \
$(BUILD_DIR)/asm/code/dddviewport3d.o \
$(BUILD_DIR)/asm/code/u3dalgebra3.o \
$(BUILD_DIR)/asm/code/U3DBox3D.o \
$(BUILD_DIR)/asm/code/U3DLight.o \
$(BUILD_DIR)/asm/code/U3DLightGroup.o \
$(BUILD_DIR)/asm/code/U3DMesh.o \
$(BUILD_DIR)/asm/code/U3DQuaternion.o \
$(BUILD_DIR)/asm/code/U3DTransform.o \
$(BUILD_DIR)/asm/code/RsrcCollection.o \
$(BUILD_DIR)/asm/code/RsrcDescriptor.o \
$(BUILD_DIR)/asm/code/RsrcMgr.o \
$(BUILD_DIR)/asm/code/RsrcPkt.o \
$(BUILD_DIR)/asm/code/RsrcSite.o \
$(BUILD_DIR)/asm/code/RsrcType.o \
$(BUILD_DIR)/asm/code/console_stubs.o \
$(BUILD_DIR)/asm/code/FSp_fopen.o \
$(BUILD_DIR)/asm/code/LException.o \
$(BUILD_DIR)/asm/code/CarbonGoodies.o \
$(BUILD_DIR)/asm/code/CarbonInterfaceLib.o \
$(BUILD_DIR)/asm/code/CarbonHelpers.o \
$(BUILD_DIR)/asm/code/XCheckForCDROM.o \
$(BUILD_DIR)/asm/code/WinDowntown.o \
$(BUILD_DIR)/asm/code/Inventory.o \
$(BUILD_DIR)/asm/code/WinProgressPictureDialog.o \
$(BUILD_DIR)/asm/code/WinInterest.o \
$(BUILD_DIR)/asm/code/WinEditDTLotDesc.o \
$(BUILD_DIR)/asm/code/WinGift.o \
$(BUILD_DIR)/asm/code/GrassTool.o \
$(BUILD_DIR)/asm/code/WinClothingChoiceDlg.o \
$(BUILD_DIR)/asm/code/WinPictureSplashDialog.o \
$(BUILD_DIR)/asm/code/AlphaBlending.o \
$(BUILD_DIR)/asm/code/MacMusicInstall.o \
$(BUILD_DIR)/asm/code/DirectoryCopy.o \
$(BUILD_DIR)/asm/code/FileCopy.o \
$(BUILD_DIR)/asm/code/MoreFilesExtras.o \
$(BUILD_DIR)/asm/code/MoreDesktopMgr.o \
$(BUILD_DIR)/asm/code/MoreFiles.o \
$(BUILD_DIR)/asm/code/MacSimsDialogs.o \
$(BUILD_DIR)/asm/code/IFFResFile3.o \
$(BUILD_DIR)/asm/code/WinVacation.o \
$(BUILD_DIR)/asm/code/Spr2aDecoder.o \
$(BUILD_DIR)/asm/code/WinPetSelectDlg.o \
$(BUILD_DIR)/asm/code/WinPhonebook.o \
$(BUILD_DIR)/asm/code/WinRadioDialog.o \
$(BUILD_DIR)/asm/code/WinSubpanelPetSkills.o \
$(BUILD_DIR)/asm/code/ObjectStrings.o \
$(BUILD_DIR)/asm/code/WinSubpanelFame.o \
$(BUILD_DIR)/asm/code/WinNeighborhoodUL.o \
$(BUILD_DIR)/asm/code/WinNeighborhoodVC.o \
$(BUILD_DIR)/asm/code/WinStudiotown.o \
$(BUILD_DIR)/asm/code/Animator.o \
$(BUILD_DIR)/asm/code/TSBufferBMPProxy.o \
$(BUILD_DIR)/asm/code/TSBufferW95.o \
$(BUILD_DIR)/asm/code/TSApp.o \
$(BUILD_DIR)/asm/code/TSBuffer.o \
$(BUILD_DIR)/asm/code/TSBufferSurfaceW95.o \
$(BUILD_DIR)/asm/code/TSCallbackThread.o \
$(BUILD_DIR)/asm/code/TSCallbackTimer.o \
$(BUILD_DIR)/asm/code/TSColor.o \
$(BUILD_DIR)/asm/code/TSCursorW95.o \
$(BUILD_DIR)/asm/code/TSDBFontKorean.o \
$(BUILD_DIR)/asm/code/TSCmdLine.o \
$(BUILD_DIR)/asm/code/TSDBFontThai.o \
$(BUILD_DIR)/asm/code/TSCheatCodeManager.o \
$(BUILD_DIR)/asm/code/TSDirectory.o \
$(BUILD_DIR)/asm/code/TSFont.o \
$(BUILD_DIR)/asm/code/TSFile.o \
$(BUILD_DIR)/asm/code/TSFontSys.o \
$(BUILD_DIR)/asm/code/TSFontGimex.o \
$(BUILD_DIR)/asm/code/TSFrameW95.o \
$(BUILD_DIR)/asm/code/TSFrame.o \
$(BUILD_DIR)/asm/code/TSGraphicSystemW95.o \
$(BUILD_DIR)/asm/code/TSGraphicSystem.o \
$(BUILD_DIR)/asm/code/TSIniFileW95.o \
$(BUILD_DIR)/asm/code/TSInterface.o \
$(BUILD_DIR)/asm/code/TSLanguage.o \
$(BUILD_DIR)/asm/code/TSKeyboard.o \
$(BUILD_DIR)/asm/code/TSMessage.o \
$(BUILD_DIR)/asm/code/TSMainWindowW95.o \
$(BUILD_DIR)/asm/code/TSScreenBufferW95.o \
$(BUILD_DIR)/asm/code/TSSimRadio.o \
$(BUILD_DIR)/asm/code/TSSnd.o \
$(BUILD_DIR)/asm/code/TSString.o \
$(BUILD_DIR)/asm/code/TSSndSys.o \
$(BUILD_DIR)/asm/code/TSSysSer.o \
$(BUILD_DIR)/asm/code/TSSystemButton.o \
$(BUILD_DIR)/asm/code/TSThread.o \
$(BUILD_DIR)/asm/code/TSTimerW95.o \
$(BUILD_DIR)/asm/code/TSWin.o \
$(BUILD_DIR)/asm/code/TSWinBtn.o \
$(BUILD_DIR)/asm/code/TSWinCheatHelp.o \
$(BUILD_DIR)/asm/code/TSWinCtrlMgr.o \
$(BUILD_DIR)/asm/code/TSWinDlg.o \
$(BUILD_DIR)/asm/code/TSWinGenDlg.o \
$(BUILD_DIR)/asm/code/TSWinIMEMgr.o \
$(BUILD_DIR)/asm/code/TSWinMgrW95.o \
$(BUILD_DIR)/asm/code/TSWinMsgBox.o \
$(BUILD_DIR)/asm/code/TSWinScrollbar.o \
$(BUILD_DIR)/asm/code/TSWinPieMenu.o \
$(BUILD_DIR)/asm/code/TSWinSlider.o \
$(BUILD_DIR)/asm/code/TSWinSplashScreen.o \
$(BUILD_DIR)/asm/code/TSWinTextEdit2.o \
$(BUILD_DIR)/asm/code/TSWinTextList.o \
$(BUILD_DIR)/asm/code/TSWinText.o \
$(BUILD_DIR)/asm/code/TSWinTutorialHighlight.o \
$(BUILD_DIR)/asm/code/TSXGlobalW95.o \
$(BUILD_DIR)/asm/code/TSXTypes.o \
$(BUILD_DIR)/asm/code/RZCPUid.o \
$(BUILD_DIR)/asm/code/RZCPUSpeed.o \
$(BUILD_DIR)/asm/code/RZFastCompression3.o \
$(BUILD_DIR)/asm/code/RZFile.o \
$(BUILD_DIR)/asm/code/RZRandom.o \
$(BUILD_DIR)/asm/code/RZString.o \
$(BUILD_DIR)/asm/code/RZVersion.o \
$(BUILD_DIR)/asm/code/RZXGlobal.o \
$(BUILD_DIR)/asm/code/RZHashString.o \
$(BUILD_DIR)/asm/code/CTGMicroTimer.o \
$(BUILD_DIR)/asm/code/CTGInt64.o \
$(BUILD_DIR)/asm/code/CTGFile2.o \
$(BUILD_DIR)/asm/code/CTGDump.o \
$(BUILD_DIR)/asm/code/CTGString.o \
$(BUILD_DIR)/asm/code/FileAlias.o \
$(BUILD_DIR)/asm/code/ImageHandle.o \
$(BUILD_DIR)/asm/code/HeadTextRenderer.o \
$(BUILD_DIR)/asm/code/CarbonCoreGraphics.o \
$(BUILD_DIR)/asm/code/GameDisplay.o \
$(BUILD_DIR)/asm/code/PreferencesDialog.o \
$(BUILD_DIR)/asm/code/MacDialogUtils.o \
$(BUILD_DIR)/asm/code/PickMonitor.o \
$(BUILD_DIR)/asm/code/MagiclandSprites.o \
$(BUILD_DIR)/asm/code/WinTransformMeDlg.o \
$(BUILD_DIR)/asm/code/WinMagicland.o \
$(BUILD_DIR)/asm/code/PickSpellList.o \
$(BUILD_DIR)/asm/code/PickSpellItem.o \
$(BUILD_DIR)/asm/code/WinMagicbook.o \
$(BUILD_DIR)/asm/code/Win32INI.o \
$(BUILD_DIR)/asm/code/code_00584B70.o \
$(BUILD_DIR)/asm/data/text0.o \
$(BUILD_DIR)/asm/data/data0.o